 package testexception;

public class Exception1 {

	public static void main(String[] args) {
		try {
		int data =121/0;}
		catch(Exception e) 
			{System.out.println(e);}
		System.out.println("revanth");
		}
	
		

}

